//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orphanage_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrphanageVisit
    {
        public System.Guid aId { get; set; }
        public string aName { get; set; }
        public string aAddress { get; set; }
        public string aContactNumber { get; set; }
        public System.DateTime aCurrenntDate { get; set; }
        public System.DateTime aScheduleDate { get; set; }
        public System.DateTime aScheduleTime { get; set; }
        public int oId { get; set; }
    
        public virtual orphanageRegistration1 orphanageRegistration1 { get; set; }
    }
}
