//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orphanage_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reqTable()
        {
            this.TransactionTables = new HashSet<TransactionTable>();
        }
    
        public string Id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public int oId { get; set; }
        public Nullable<decimal> Deposited { get; set; }
    
        public virtual orphanageRegistration1 orphanageRegistration1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionTable> TransactionTables { get; set; }
    }
}
