//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orphanage_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int tId { get; set; }
        public int oId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public decimal Amount { get; set; }
    
        public virtual orphanageRegistration1 orphanageRegistration1 { get; set; }
    }
}
